server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/template_db?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: xxxxxx
    hikari:
      connection-timeout: 30000       #等待连接池分配连接的最大时间（毫秒），超时
      minimum-idle: 5                 #最小链接数
      maximum-pool-size: 20           #最大连接数
      auto-commit: true               #自动提交
      idle-timeout: 600000            #连接超时的最大时长（毫秒），超时则会被释放
      pool-name: DataSourceHikariCP   #连接池的名字
      max-lifetime: 18000000          #连接池的最大生命时长（毫秒），超时则会被释放
      connection-test-query: SELECT 1
  application:
    name: template

logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id
    banner: false